### ISSUE TITLE
How to run this demo?

### ISSUE THREAD

**Issue by sunhailin-Leo** [michaelschnyder/SkypeClient#1]
* I want to know why i ran the demo then got the message "Parameters mismatch".

**Comment by michaelschnyder** [comment]
Hi @sunhailin-Leo,

The demo requires user name and password to be passed as two parameters to the executable. You can check the code at https://github.com/michaelschnyder/SkypeClient/blob/master/Skype.Client.Demo/Program.cs#L44 where the two parameters are used to login.

Hope that helps

**Comment by mzayarnyuk** [comment]
are you sure it still work....
I think ms changed auth flow in last years few times
